<?php
/**
 * @file
 * Main file for the Yandex.Share Ex module.
 */

define('YASHAREX_SMALL', 1);

/**
  * Implements hook_menu(). 
  */
function yasharex_menu() {
  $items = array();
  $items['admin/config/services/yasharex'] = array(
    'title' => 'Yandex.Share Ex',
    'description' => 'Adjust Yandex.Share Ex buttons options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('yasharex_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'yasharex.admin.inc',
  );
  return $items;
}

/**
  * Implements hook_block_info(). 
  */
function yasharex_block_info() {
  $blocks['yasharex'] = array(
    'info' => t('Yandex.Share Ex'),
    'status' => FALSE,
    'weight' => 10,
  );
  return $blocks;
}

/**
  * Implements hook_block_view(). 
  */
function yasharex_block_view($delta = '') {
  $block = array();
  if ($delta == 'yasharex') { 
    $block['subject'] = t('Share');
    $block['content'] = array(
      '#markup' => yasharex_block_content(),
      '#attached' => array(
        'js' => array(
          '//yandex.st/share/cnt.share.js' => array(
            'type' => 'external',
          ),
        ),
      ),
    );
  }
  return $block;
}

function yasharex_block_content() {
  global $language_content;
  $lang = $language_content->language;
  
  $block_content = '<div class="yashare-auto-init"';
  $block_content .= ' data-yashareL10n="' . $lang . '"';

  $service_list = ' data-yashareQuickServices="';
  foreach (yasharex_services_list() as $service_id => $service_name) {
    if (variable_get('yasharex_service_' . $service_id . '_enabled', 1)) {
      $service_list .= $service_id . ',';
    }
  }
  $service_list .= '"';
  $block_content .= $service_list;
  //$block_content .= ' data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,gplus"';

  if (variable_get('small_size', YASHAREX_SMALL)) {
    $block_content .= ' data-yashareType="small"';
  }
  $block_content .= ' data-yashareTheme="counter" /></div>';
  return $block_content;
}

/**
 * Implements hook_theme().
 */
function yasharex_theme() {
  return array(
    'yasharex_admin_settings_services_table' => array(
      'file' => 'yasharex.admin.inc',
      'render element' => 'form',
    ),
  );
}

/**
 * Internal function.
 */
function yasharex_services_list() {
  $services = &drupal_static(__FUNCTION__, NULL);

  if (!isset($services)) {
    $raw_services = array(
      // Core providers.
      'yaru' => t('Ya.ru'),
      'vkontakte' => t('Vkontakte'),
      'facebook' => t('Facebook'),
      'twitter' => t('Twitter'),
      'odnoklassniki' => t('Odnoklassniki'),
      'moimir' => t('Moi mir'),
      'gplus' => t('Google Plus'),
      'lj' => t('Livejournal'),
      'friendfeed' => t('FriendFeed'),
      'moikrug' => t('Moi krug'),
    );

    $services = array();
    $weights = array();

    foreach ($raw_services as $service_id => $service_name) {
      $weights[$service_id] = variable_get('yasharex_service_' . $service_id . '_weight', 0);
    }
    asort($weights);

    foreach ($weights as $service_id => $weight) {
      $services[$service_id] = $raw_services[$service_id];
    }
  }

  return $services;
}